"""Gradient-based parameter optimization algorithms.

This module provides the optimizer interfaces and concrete update rules used to adjust
shared parameter buffers during training.
"""

from __future__ import annotations
import numpy as np
from abc import ABC, abstractmethod
from typing import override, Optional

class InitializationException(Exception):
    """Custom exception raised for initialization errors in the optimizer."""
    
    def __init__(self, *args):
        """Initializes the InitializationException."""
        super().__init__(*args)


class GradientOptimizer(ABC):
    """Base abstract class for gradient-based optimizers."""
    
    def __init__(self, maximise: bool = True):
        """Initializes the base optimizer.

        Args:
            maximise (bool, optional): If True, performs gradient ascent (maximization). 
                If False, performs gradient descent (minimization). Defaults to True.
        """
        self.__maximise = maximise
        
    @property
    def maximise(self) -> bool:
        return self.__maximise
        
    @maximise.setter
    def maximise(self, value: bool):
        if not isinstance(value, bool):
            raise TypeError("`maximise` can only be type bool")
        self.__maximise = value
        
    @abstractmethod
    def step(self, gradient: np.ndarray):
        """Performs a single optimization step.

        Args:
            gradient (np.ndarray): The gradient of the objective function with respect 
                to the parameters.
        """
        ...
        
    @abstractmethod
    def initialize(self, params: np.ndarray, weight_mask: Optional[np.ndarray] = None) -> None:
        """Initializes the optimizer with the parameter buffer.

        Args:
            params (np.ndarray): The parameter array to be optimized.
            weight_mask (Optional[np.ndarray], optional): An optional mask applied to 
                parameters during specific updates (e.g., weight decay). Defaults to None.
        """
        ...

    @abstractmethod
    def state(self) -> dict:
        """Retrieves the current internal state of the optimizer.

        Returns:
            dict: A dictionary containing optimizer-specific state variables.
        """
        ...

    @abstractmethod
    def load_state(self, state: dict) -> None:
        """Loads the optimizer state from a previously saved dictionary.

        Args:
            state (dict): The state dictionary generated by the `state` method.
        """
        ...


class SGD(GradientOptimizer):
    """Stochastic Gradient Descent (or Ascent) optimizer."""
    
    def __init__(self, maximise: bool = True, alpha: float = 0.001):
        """Initializes the SGD optimizer.

        Args:
            maximise (bool, optional): Whether to maximize or minimize the objective. Defaults to True.
            alpha (float, optional): The learning rate. Defaults to 0.001.
        """
        super().__init__(maximise=maximise)
        self.__alpha = alpha
        self.__initialized = False
        self.__params = None
        
    @property
    def initialized(self) -> bool:
        return self.__initialized
    @initialized.setter
    def initialized(self, value: bool):
        if not isinstance(value, bool):
            raise TypeError("initialized can only be type bool")
        self.__initialized = value

    @property
    def alpha(self) -> float:
        return self.__alpha

    @alpha.setter
    def alpha(self, value: float | int):
        if not isinstance(value, (int, float)): 
            raise TypeError("alpha must be a float or int")
        self.__alpha = float(value)

    @property
    def params(self) -> np.ndarray:
        return self.__params

    @params.setter
    def params(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): 
            raise TypeError("params must be a numpy array")
        self.__params = value

    @override
    def step(self, gradient: np.ndarray):
        """Performs a single SGD optimization step.

        Args:
            gradient (np.ndarray): The computed gradient array.

        Raises:
            InitializationException: If the optimizer has not been initialized with parameters.
        """
        if not self.__initialized:
            raise InitializationException("The Optimizer has never been initialized")
        
        if self.maximise:
            self.__params += gradient * self.__alpha
        else:
            self.__params -= gradient * self.__alpha
            
    @override
    def initialize(self, params: np.ndarray, weight_mask: Optional[np.ndarray] = None):
        """Initializes the SGD optimizer with the parameters.

        Args:
            params (np.ndarray): The parameter buffer to optimize.
            weight_mask (Optional[np.ndarray], optional): Unused in basic SGD, provided 
                for interface compatibility. Defaults to None.
        """
        self.__params = params
        self.__initialized = True
    
    def state(self) -> dict:
        """Retrieves the state of the SGD optimizer.

        Returns:
            dict: An empty dictionary, as basic SGD maintains no internal moving averages.
        """
        return {}

    def load_state(self, state: dict) -> None:
        """Loads the state of the SGD optimizer.

        Args:
            state (dict): The state dictionary.
        """
        pass


class Adam(GradientOptimizer):
    """Adam (Adaptive Moment Estimation) optimizer."""
    
    def __init__(self, maximise: bool = True, alpha: float = 0.01, beta1: float = 0.9, beta2: float = 0.999, epsilon: float = 1e-8):
        """Initializes the Adam optimizer.

        Args:
            maximise (bool, optional): Whether to maximize or minimize the objective. Defaults to True.
            alpha (float, optional): The learning rate (step size). Defaults to 0.01.
            beta1 (float, optional): The exponential decay rate for the first moment estimates. Defaults to 0.9.
            beta2 (float, optional): The exponential decay rate for the second-moment estimates. Defaults to 0.999.
            epsilon (float, optional): A small constant for numerical stability. Defaults to 1e-8.
        """
        super().__init__(maximise=maximise)
        self.__alpha = alpha
        self.__beta1 = beta1
        self.__beta2 = beta2
        self.__epsilon = epsilon
        self.__initialized = False
        self.__params = None
        self.__m = None
        self.__v = None
        self.__m_hat = None
        self.__v_hat = None
        self.__t = 0

    # Hyperparameter Properties
    @property
    def initialized(self) -> bool:
        return self.__initialized
    @initialized.setter
    def initialized(self, value: bool):
        if not isinstance(value, bool):
            raise TypeError("initialized can only be type bool")
        self.__initialized = value
    @property
    def alpha(self) -> float: return self.__alpha
    @alpha.setter
    def alpha(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("alpha needs to be a float or an int")
        self.__alpha = float(value)

    @property
    def beta1(self) -> float: return self.__beta1
    @beta1.setter
    def beta1(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("beta1 needs to be a float or an int")
        self.__beta1 = float(value)

    @property
    def beta2(self) -> float: return self.__beta2
    @beta2.setter
    def beta2(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("beta2 needs to be a float or an int")
        self.__beta2 = float(value)

    @property
    def epsilon(self) -> float: return self.__epsilon
    @epsilon.setter
    def epsilon(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("epsilon needs to be a float or an int")
        self.__epsilon = float(value)

    # State Properties
    @property
    def t(self) -> int: return self.__t
    @t.setter
    def t(self, value: int):
        if not isinstance(value, int): raise TypeError("t must be an integer")
        self.__t = value

    @property
    def params(self) -> np.ndarray: return self.__params
    @params.setter
    def params(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("params must be a numpy array")
        self.__params = value

    @property
    def m(self) -> np.ndarray: return self.__m
    @m.setter
    def m(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("m must be a numpy array")
        self.__m = value

    @property
    def v(self) -> np.ndarray: return self.__v
    @v.setter
    def v(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("v must be a numpy array")
        self.__v = value

    @property
    def m_hat(self) -> np.ndarray: return self.__m_hat
    @m_hat.setter
    def m_hat(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("m_hat must be a numpy array")
        self.__m_hat = value

    @property
    def v_hat(self) -> np.ndarray: return self.__v_hat
    @v_hat.setter
    def v_hat(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("v_hat must be a numpy array")
        self.__v_hat = value

    @override
    def initialize(self, params: np.ndarray, weight_mask: Optional[np.ndarray] = None):
        """Initializes the Adam optimizer and allocates its moment buffers.

        Args:
            params (np.ndarray): The parameter array to be optimized.
            weight_mask (Optional[np.ndarray], optional): Unused in basic Adam. Defaults to None.
        """
        if self.__initialized:  
            self.__params = params
            return
        self.__params = params
        self.__m = np.zeros_like(params)
        self.__v = np.zeros_like(params)
        self.__m_hat = np.zeros_like(params)
        self.__v_hat = np.zeros_like(params)
        self.__t = 0
        self.__initialized = True
    
    @override
    def step(self, gradient: np.ndarray) -> None:
        """Performs a single Adam optimization step.

        Args:
            gradient (np.ndarray): The computed gradient array.

        Raises:
            InitializationException: If the optimizer has not been initialized.
        """
        if not self.__initialized:
            raise InitializationException("The Optimizer has never been initialized")
        
        self.__t += 1
        self.__m = self.__beta1 * self.__m + (1 - self.__beta1) * gradient
        self.__v = self.__beta2 * self.__v + (1 - self.__beta2) * gradient**2
        self.__m_hat = self.__m / (1 - self.__beta1**self.__t)
        self.__v_hat = self.__v / (1 - self.__beta2**self.__t)
        
        update = self.__alpha * (self.__m_hat / (np.sqrt(self.__v_hat) + self.__epsilon))
        if self.maximise:
            self.__params += update
        else:
            self.__params -= update

    def state(self) -> dict:
        """Retrieves the internal state of the Adam optimizer.

        Returns:
            dict: A dictionary containing copies of the first moment (`m`), 
                second moment (`v`), and time step (`t`).
        """
        return {
            "m": self.__m.copy(),
            "v": self.__v.copy(),
            "t": self.__t
        }

    def load_state(self, state: dict) -> None:
        """Loads the internal state of the Adam optimizer.

        Args:
            state (dict): The state dictionary containing `m`, `v`, and `t`.
        """
        self.__m = state["m"]
        self.__v = state["v"]
        self.__t = int(state["t"])
        self.__m_hat = np.zeros_like(self.__m)
        self.__v_hat = np.zeros_like(self.__v)
        self.__initialized = True


class AdamW(GradientOptimizer):
    """AdamW (Adam with Weight Decay) optimizer."""
    
    def __init__(self, maximise: bool = True, alpha: float = 0.01, weight_decay: float = 0.0,
                 grad_clip: float = float("inf"), beta1: float = 0.9, beta2: float = 0.999, epsilon: float = 1e-8):
        """Initializes the AdamW optimizer.

        Args:
            maximise (bool, optional): Whether to maximize or minimize the objective. Defaults to True.
            alpha (float, optional): The learning rate (step size). Defaults to 0.01.
            weight_decay (float, optional): The decoupled weight decay factor. Defaults to 0.0.
            grad_clip (float, optional): The maximum allowed L2 norm of the gradient. Defaults to infinity.
            beta1 (float, optional): The exponential decay rate for the first moment estimates. Defaults to 0.9.
            beta2 (float, optional): The exponential decay rate for the second-moment estimates. Defaults to 0.999.
            epsilon (float, optional): A small constant for numerical stability. Defaults to 1e-8.
        """
        super().__init__(maximise=maximise)
        self.__alpha = alpha
        self.__beta1 = beta1
        self.__beta2 = beta2
        self.__epsilon = epsilon
        self.__grad_clip = grad_clip
        self.__weight_decay = weight_decay
        self.__initialized = False
        
        self.__params = None
        self.__weight_mask = None
        self.__m = None
        self.__v = None
        self.__m_hat = None
        self.__v_hat = None
        self.__t = 0

    # Hyperparameter Properties
    @property
    def initialized(self) -> bool:
        return self.__initialized
    @initialized.setter
    def initialized(self, value: bool):
        if not isinstance(value, bool):
            raise TypeError("initialized can only be type bool")
        self.__initialized = value
    @property
    def alpha(self) -> float: return self.__alpha
    @alpha.setter
    def alpha(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("alpha needs to be a float or an int")
        self.__alpha = float(value)

    @property
    def beta1(self) -> float: return self.__beta1
    @beta1.setter
    def beta1(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("beta1 needs to be a float or an int")
        self.__beta1 = float(value)

    @property
    def beta2(self) -> float: return self.__beta2
    @beta2.setter
    def beta2(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("beta2 needs to be a float or an int")
        self.__beta2 = float(value)

    @property
    def epsilon(self) -> float: return self.__epsilon
    @epsilon.setter
    def epsilon(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("epsilon needs to be a float or an int")
        self.__epsilon = float(value)

    @property
    def grad_clip(self) -> float: return self.__grad_clip
    @grad_clip.setter
    def grad_clip(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("grad_clip needs to be a float or an int")
        self.__grad_clip = float(value)

    @property
    def weight_decay(self) -> float: return self.__weight_decay
    @weight_decay.setter
    def weight_decay(self, value: float | int):
        if not isinstance(value, (int, float)): raise TypeError("weight_decay needs to be a float or an int")
        self.__weight_decay = float(value)

    # State Properties
    @property
    def t(self) -> int: return self.__t
    @t.setter
    def t(self, value: int):
        if not isinstance(value, int): raise TypeError("t must be an integer")
        self.__t = value

    @property
    def params(self) -> np.ndarray: return self.__params
    @params.setter
    def params(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("params must be a numpy array")
        self.__params = value

    @property
    def weight_mask(self) -> np.ndarray: return self.__weight_mask
    @weight_mask.setter
    def weight_mask(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("weight_mask must be a numpy array")
        self.__weight_mask = value

    @property
    def m(self) -> np.ndarray: return self.__m
    @m.setter
    def m(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("m must be a numpy array")
        self.__m = value

    @property
    def v(self) -> np.ndarray: return self.__v
    @v.setter
    def v(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("v must be a numpy array")
        self.__v = value

    @property
    def m_hat(self) -> np.ndarray: return self.__m_hat
    @m_hat.setter
    def m_hat(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("m_hat must be a numpy array")
        self.__m_hat = value

    @property
    def v_hat(self) -> np.ndarray: return self.__v_hat
    @v_hat.setter
    def v_hat(self, value: np.ndarray):
        if not isinstance(value, np.ndarray): raise TypeError("v_hat must be a numpy array")
        self.__v_hat = value

    @override
    def initialize(self, params: np.ndarray, weight_mask: Optional[np.ndarray] = None):
        """Initializes the AdamW optimizer with parameters and a weight decay mask.

        Args:
            params (np.ndarray): The parameter array to be optimized.
            weight_mask (Optional[np.ndarray], optional): An array of the same shape 
                as `params` used to mask specific parameters from weight decay updates. 
                Defaults to an array of ones if not provided.
        """
        if self.__initialized:
            self.__params = params
            return
            
        self.__weight_mask = weight_mask if weight_mask is not None else np.ones_like(params)
        self.__params = params
        self.__m = np.zeros_like(params)
        self.__v = np.zeros_like(params)
        self.__m_hat = np.zeros_like(params)
        self.__v_hat = np.zeros_like(params)
        self.__t = 0
        self.__initialized = True
    
    @override
    def step(self, gradient: np.ndarray) -> None:
        """Performs a single AdamW optimization step, applying weight decay and gradient clipping.

        Args:
            gradient (np.ndarray): The computed gradient array.

        Raises:
            InitializationException: If the optimizer has not been initialized.
        """
        if not self.__initialized:
            raise InitializationException("The Optimizer has never been initialized")
        
        gradient_norm = np.linalg.norm(gradient)
        if gradient_norm > self.__grad_clip:
            gradient = self.__grad_clip * (gradient / (gradient_norm + 1e-6))
        
        self.__t += 1
        self.__m = self.__beta1 * self.__m + (1 - self.__beta1) * gradient
        self.__v = self.__beta2 * self.__v + (1 - self.__beta2) * gradient**2
        self.__m_hat = self.__m / (1 - self.__beta1**self.__t)
        self.__v_hat = self.__v / (1 - self.__beta2**self.__t)
        
        if self.__weight_decay > 0.0:
            self.__params -= (self.__alpha * self.__weight_decay * self.__params * self.__weight_mask)
        
        update = self.__alpha * (self.__m_hat / (np.sqrt(self.__v_hat) + self.__epsilon))
        if self.maximise:
            self.__params += update
        else:
            self.__params -= update

    def state(self) -> dict:
        """Retrieves the internal state of the AdamW optimizer.

        Returns:
            dict: A dictionary containing copies of the first moment (`m`), 
                second moment (`v`), and time step (`t`).
        """
        return {
            "m": self.__m.copy(),
            "v": self.__v.copy(),
            "t": self.__t
        }

    def load_state(self, state: dict) -> None:
        """Loads the internal state of the AdamW optimizer.

        Args:
            state (dict): The state dictionary containing `m`, `v`, and `t`.
        """
        self.__m = state["m"]
        self.__v = state["v"]
        self.__t = int(state["t"])
        self.__m_hat = np.zeros_like(self.__m)
        self.__v_hat = np.zeros_like(self.__v)
        self.__initialized = True